const menu = [
    {
      id: 1,
      title: 'buttermilk pancakes',
      category: 'breakfast',
      price: 15.99,
      img: 'https://www.browneyedbaker.com/wp-content/uploads/2021/06/buttermilk-pancakes-8-square.jpg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 2,
      title: 'diner double',
      category: 'lunch',
      price: 13.99,
      img: 'https://images.squarespace-cdn.com/content/v1/5e7a6c3e8fe74049a7982934/1585083247445-1WUFX11L3GEH8JTCAR2L/IMG_6630-white-background.jpg',
      desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
    },
    {
      id: 3,
      title: 'godzilla milkshake',
      category: 'shakes',
      price: 6.99,
      img: 'https://media-cdn.tripadvisor.com/media/photo-m/1280/1c/c2/29/eb/milo-godzilla.jpg',
      desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    },
    {
      id: 4,
      title: 'country delight',
      category: 'breakfast',
      price: 20.99,
      img: 'https://rajmenu.netlify.app/images/item-4.jpeg',
      desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    },
    {
      id: 5,
      title: 'egg attack',
      category: 'lunch',
      price: 22.99,
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJoWfBqSeYr1FCZGTJ8wkGu4QzaSE3AHab-Q&s',
      desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
    },
    {
      id: 6,
      title: 'oreo dream',
      category: 'shakes',
      price: 18.99,
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR1bDK2oaEb1Q-v7BGR5IBrTSHrt9gOCna8pw&s',
      desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
      id: 7,
      title: 'bacon overflow',
      category: 'breakfast',
      price: 8.99,
      img: 'https://www.foodandwine.com/thmb/4jGVuIAGewGY6aHv7V2-A-w_uf8=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/lobster-blts-on-potato-rolls-FT-RECIPE0620-ed6bf2d639264530938a33093054415e.jpg',
      desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
    },
    {
      id: 8,
      title: 'american classic',
      category: 'lunch',
      price: 12.99,
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQk3vDSyHF85kCZHEtBcZtaYSoEKEBvq0zaxg&s',
      desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    },
    {
      id: 9,
      title: 'quarantine buddy',
      category: 'shakes',
      price: 16.99,
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNDo540zjTXgTR2-tDGH6x676iazcP6LSxMA&s',
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
  ];
  export default menu;